Proceso CALCULADORA 
	DEFINIR N1,N2,R,S,M,D Como Entero;
	Escribir "INGRESE EL PRIMER NÚMERO ";
	LEER N1 ;
	ESCRIBIR "INGRESE EL SEGUMDO NÚMERO ";
	LEER N2 ;
	R<-N1-N2;
	S<-N1+N2 ;
	M<-N1*N2;
	D<-N1/N2;
	Escribir "LA SUMA ES ",S;
	ESCRIBIR "LA RESTA ES ",R;
	ESCRIBIR "LA MULTPLICACIÓN ES ",M ;
	ESCRIBIR "LA DIVISIÓN ES ",D;
FinProceso
