Proceso PROMEDIO
	DEFINIR N1,N2,N3,N4,P Como REAL;
	ESCRIBIR "INGRESE SU PRIMERA NOTA ";
	LEER N1 ;
	ESCRIBIR " INGRESE SU SEGUNDA NOTA ";
	LEER N2;
	ESCRIBIR "INGRESE SU TERCERA NOTA ";
	LEER N3;
	Escribir "INGRESE SU CUARTA NOTA ";
	LEER N4;
	P<-(N1+N2+N3+N4)/4;
	Escribir "SU PROMEDIO ES ",P;
FinProceso
